### ISSUE TITLE
ValueError with typing.Union type signature

### ISSUE THREAD

**Issue by wangkev** [stitchfix/hamilton#170]
`hamilton` raises a `ValueError` when using `typing.Union`, even if the type signature has the input type.

# Current behavior
Error when using `typing.Union` types.

## Stack Traces
```
ValueError: 1 errors encountered:
  Error: Type requirement mismatch. Expected x:typing.Union[int, pandas.core.series.Series] got 1 instead.
```

## Steps to replicate behavior
`run.py`
```python
from hamilton.driver import Driver
from hamilton.base import SimplePythonGraphAdapter, DictResult
import lib

initial_columns = {'x': 1}
adapter = SimplePythonGraphAdapter(DictResult)
dr = Driver(initial_columns, lib, adapter=adapter)
print(dr.execute(['foo_union']))
```

`lib.py`
```python
import typing as t
import pandas as pd


def foo_union(x: t.Union[int, pd.Series]) -> t.Union[int, pd.Series]:
    '''foo union'''
    return x + 1
```

## Library & System Information
python 3.6, hamilton 1.9.0, tested on mac and linux.

# Expected behavior
To be able to run dag.

# Additional context
Everything works if there are functions that have `typing.Any` as type signature. For example, the above will run if we add `foo_any` to `lib.py`:

```python
import typing as t
import pandas as pd


def foo_union(x: t.Union[int, pd.Series]) -> t.Union[int, pd.Series]:
    '''foo union'''
    return x + 1


def foo_any(x: t.Any) -> t.Any:
    '''foo any'''
    return x + 1
```

**Comment by skrawcz** [comment]
Thanks @wangkev ! I believe I punted on this.

Question -- why union support? You don't want to write two functions and delegate to a helper? or?

**Comment by skrawcz** [comment]
@wangkev want to give this branch a spin too? https://github.com/stitchfix/hamilton/pull/173 
It should fix this issue.

**Comment by skrawcz** [comment]
@wangkev I think going from subset to superset is fine. But going from superset to subset is asking for errors.

E.g. I think this should be fine:
```python
def bar(x: int) -> int:
    return x
def foo_bar_union(bar: t.Union[int, pd.Series]) -> t.Union[int, pd.Series]:
    return bar + 1
```
But this should not:
```python
def bar(x: t.Union[int, pd.Series]) -> t.Union[int, pd.Series]:
    return x
def foo_bar_union(bar: int]) -> int:
    return bar + 1
```

In the case of `Any` if you're connecting to something downstream -- then you should really propagate `Any` all the way through, or have an identity type function that casts things to a specific type. Otherwise someone will end up debugging a downstream function and wonder why they're getting errors and something that does not conform to the specified type annotation. Note: Hamilton only uses this for DAG instantiation, come run time there are no checks, unless you use the `@check_output` decorator.

**Comment by skrawcz** [comment]
> On the other hand, I kind of feel like it should still work. At the very least, it does not seem like the right solution nor pythonic to wrap the function just to have a different type signature. 

Sure, but Hamilton is a framework that is trying to make it hard to shoot oneself in the foot :) i.e. code lives for a lot longer, and it should be obvious if not easy to ramp up for someone who doesn't know the code what is going on; it would be more verbose, but simpler to maintain is my hypothesis.

> Maybe it is sufficient to make it a warning and not cause an error? Or is there some typing (or decorator) magic to specify output type is the input type?

So good news is, that with graph adapters, one could augment this behavior quite easily, without it being a framework default; it could be a framework supported option though. Power users such as yourself, could tell Hamilton, e.g. allow static DAG construction to allow `Any` to be a valid input into any function argument. CC @elijahbenizzy .  I have some changes to do on my PR, but that might be the easiest way to give you what you want; will prototype how it feels myself first. 

Question @wangkev how urgent is this for you?

**Comment by elijahbenizzy** [comment]
> Not that urgent. Supporting union type hints is more important for now.

Awesome, I'll be seeing that across the finish line shortly as Stefan will be out for a bit.

**Comment by skrawcz** [comment]
@wangkev @elijahbenizzy will get a release candidate out today/tomorrow -- with a likely full release later in the week. If you have cycles would love to you verify the release candidate when it comes out.

Otherwise created https://github.com/stitchfix/hamilton/issues/181 to track supporting what we just discussed.

**Comment by elijahbenizzy** [comment]
Hey @wangkev -- rc out!  `pip install sf-hamilton==1.10.0rc0`. Happy to fix any bugs, planning on a general release shortly.
