### ISSUE TITLE
Enhancement: Add capability to use a DataFrame as the basis for Driver `initial_columns`

### ISSUE THREAD

**Issue by straun** [stitchfix/hamilton#18]
Currently the Driver `initial_columns` accepts a Dict which maps the column names to a Series. If you already have a DataFrame then why not support a Driver constructor that accepts the DataFrame?

Without this, the caller is required to create a Dict themselves by iterating over the column names and using `squeeze` to generate a Series for each.

**Comment by skrawcz** [comment]
I am leaning toward moving forward with this idea because it would simplify "driver chaining".

Motivation: you either have to have a separate because you want to do something, like wide to long transform, or have conflicting module function names:

# Proposal
Right now you'd have to do this

```python
dr = driver.Driver(config_or_data, modules)
long_df = dr.execute(['col1', ..., 'col3']).melt(...)
dr2 = driver.Driver({key: initial_df[key] for key in long_df}, modules).  # < -- this line is what I'm talking about
df2 = dr2.execute(['colX', ..., 'colY'])
```
Proposing this becomes:
```python
dr = driver.Driver(config_or_data, modules)
long_df = dr.execute(['col1', ..., 'col3']).melt(...)
dr2 = driver.Driver(long_df, modules) # < -- this line is now simplified
df2 = dr2.execute(['colX', ..., 'colY'])
```

# edge cases
## @config.when likely wont work
Since @config.when operates on scalars, you wouldn't be able to exercise functions decorated with this, as the dataframe has only columns...

# Alternative
We instead push people to @chmp's solution -- which means that we never confuse users with how to provide inputs to the driver.

**Comment by skrawcz** [comment]
Closing this issue for now. Since we haven't received much feedback on this. Also Hamilton now supports more than just creating dataframes, so perhaps this would result in overcoupling to dataframes when we don't want there to be such tight coupling.
