### ISSUE TITLE
Alert when functions are overwritten

### ISSUE THREAD

**Issue by ropeladder** [stitchfix/hamilton#193]
**Is your feature request related to a problem? Please describe.**
I'm not sure how this would actually work but it would be helpful to have a check for duplicate function definitions. I just ran into this:

```
@parameterize(output1={"arg1": value(pd.Series()), "arg2": value(pd.Series())})
def test_conflict(arg1: pd.Series, arg2: pd.Series) -> pd.Series:
	return arg1

@parameterize(output2={"arg3": value(pd.Series()), "arg4": value(pd.Series())})
def test_conflict(arg3: pd.Series, arg4: pd.Series) -> pd.Series:
	return arg3

def final(output1: pd.Series) -> pd.Series:
	return output1
```

The error message just tells you that `output1` isn't defined, which is because `test_conflict()` is getting overwritten. Given that the function names are meaningless when you use `@parameterize`, it's fairly easy to forget to change them and end up with a confusing error.

**Describe the solution you'd like**
Ideally something that would check for duplicate function definitions, at least for ones that are parameterized.

**Describe alternatives you've considered**
Obviously linters help with this as well.

**Comment by skrawcz** [comment]
@ropeladder thanks.

Yes I see two errors:

1. `test_conflict` is defined twice -- which I think we should be able to catch. Let me check that.
2.  `arg1` is returned for the second function, but there is no `arg1` defined in the function -- I'm not sure we'll be able to catch this issue well because it would involve inspecting python. Ideally we'd get you to write a unit test which would catch it, but I'll noodle on it. 🤔  Your IDE should help catch this one too...

**Comment by ropeladder** [comment]
Ah, (2) is just me forgetting to edit some of my code. I fixed the example.

**Comment by skrawcz** [comment]
@ropeladder sorry, bad news. Without writing a lot of code, we're not going to be able to catch this issue easily.

We internally depend on `inspect.getmembers` to get functions from modules - https://github.com/stitchfix/hamilton/blob/main/hamilton/graph.py#L38.

Which in turn depends on python's native `dir()` function -  https://github.com/python/cpython/blob/3.10/Lib/inspect.py#L444-L453 which returns a dictionary -- where multiple keys are obviously not allowed -- and we only get returned one thing with that particular name.

So without doing module importing and AST parsing ourselves (non-trivial amount of code), we don't actually get returned multiple functions to know there are duplicates. So going to close this issue out because it's too much code to write for the problem at hand.
