### ISSUE TITLE
Specify path to save .gv files

### ISSUE THREAD

**Issue by latlan1** [stitchfix/hamilton#45]
## Current & Expected behavior
I wish there was a way of specifying the path for saving the DAG (.gv). I had two sets of DAGs and the file gets overwritten as test_output/execute.gv.

## Library & System Information
python version= 3.7.11, hamilton library version =1.1.1, linux= yes, Ubuntu 20 installed via WSL 1

**Comment by skrawcz** [comment]
# Proposed API - split display out into a `visualize_execute` function
Reasoning -- much like the `explain` functionality in a DB -- we should expose an 'visualize_execute' function in the driver.
I don't want to call it `explain` because it's not obvious what to expect. I think `visualize_execute` is better.

In future if we add an `explain` functionality, it could delegate to this function for instance.

```python

class Driver(object):
    ...
    def visualize_execute(self, final_vars: List[str],
                overrides: Dict[str, Any] = None, output_file_uri: str,  **render_kwargs):
          """render_kwargs would be passed through to the graphviz render function"""
```

## deprecate display_graph in driver.execute
1 . We should deprecate this -- and tell people to move to the above function.
2. We should remove the cycle check that was thrown into the display function and move to it's own function.

**Comment by skrawcz** [comment]
This has been merged to `main`. This will come out in the `1.3.0` release.
